### ISSUE TITLE
Generic COM Exception. Code is 0x800706F7. Lync 2013 SDK

### ISSUE THREAD

**Issue by sbrian26** [tomorgan/Lync-UISuppression-VideoAutoAnswer#5]
I've recompiled the project to work with Lync 2013 SDK however cannot overcome this issue

A first chance exception of type 'Microsoft.Lync.Model.LyncClientException' occurred in Microsoft.Lync.Model.dll
Microsoft.Lync.Model.LyncClientException: Generic COM Exception. Code is 0x800706F7.
   at Microsoft.Lync.Model.Conversation.AudioVideo.VideoWindow.set_Owner()

when calling    LyncObject.Owner = value;  in class class LyncVideoWindow

**Comment by alexanderpreston** [comment]
I've actually already done this work to get Tom's library working with Lync 2013 - I really should have pushed it up to GitHub but I got busy. Will try and do it today for you.

**Comment by sbrian26** [comment]
I have discovered that this was a build target issue.  Since I had Office 2013 x64 installed on my development machine I could not install the x86 version of Lync. I converted this solution to use the Lync 2013 SDK with no issues however the project was targeting the x86 platform.   

Apparently the platform mismatch when running a x86 client against Lync x64 in UISuppressionMode causes the COM Exception when attempting to set the owner of the VideoWindow.  

Most other things controlling Lync (even with the platform mismatch) appeared to work correctly even with the client platform target mismatch.  

My Solution was to re-target the outer consuming project to x64 and set this project to build to "Any".

That said I am still seeing issues with proper video setup upon answering video calls with this and other samples targeting Lync 2013 SDK in UI Suppression Mode. Perhaps there are some different (from Lync 2010) timing issues particularly after establishing the conversation and sending the local video that are different with Lync SDK 2013 -- but again, this is another issue altogether.

**Comment by alexanderpreston** [comment]
I actually remember there was a strange behaviour when running Visual
Studio (or I guess the app directly) with or without Administrator rights.
So if you are seeing strange behaviour try running as admin (or not as
admin). Sorry can't recall the detail about this.
